cube: CST Activity Config
views:
  - view_name: RPT Default
    set_as_default: true
    mdx: |
      SELECT
      NON EMPTY {
        STRTOMEMBER("[GBL Period].[" + [GBL Version].CURRENTMEMBER.PROPERTIES("Start Period") + "]")
        :
        STRTOMEMBER("[GBL Period].[" + [GBL Version].CURRENTMEMBER.PROPERTIES("End Period") + "]")
      } ON 0,
      NON EMPTY {
        [CST Activity].[CST Activity].MEMBERS
      } * {
        [CST Driver].[CST Driver].MEMBERS
      } * {
        [CST Service Line].[CST Service Line].MEMBERS
      } ON 1
      FROM [CST Activity Config]
      WHERE (
        [GBL Version].[GBL Version].[Budget],
        [CST Activity Config Measure].[CST Activity Config Measure].[Activity to Service Line Basis]
      )
