cube: CST Apportionment Reconciliation
views:
  - view_name: RPT Default
    set_as_default: true
    mdx: |
      SELECT
      {
        STRTOMEMBER("[GBL Period].[" + [GBL Version].[Budget].PROPERTIES("Start Period") + "]")
        :
        STRTOMEMBER("[GBL Period].[" + [GBL Version].[Budget].PROPERTIES("End Period") + "]")
      } ON 0,
      {
        TM1FILTERBYLEVEL(TM1SUBSETALL([CST Reconciliation Check]), 0)
      } * {
        TM1FILTERBYLEVEL(TM1SubsetAll([CST Apportionment Reconciliation Measure].[CST Apportionment Reconciliation Measure]), 0)
      } ON 1
      FROM [CST Apportionment Reconciliation]
      WHERE (
        [GBL Version].[GBL Version].[Budget])
