cube: CST Pool to Activity Apportionment
views:
  - view_name: RPT Default
    set_as_default: true
    mdx: |
      SELECT
      NON EMPTY {
        STRTOMEMBER("[GBL Period].[" + [GBL Version].CURRENTMEMBER.PROPERTIES("Start Period") + "]")
        :
        STRTOMEMBER("[GBL Period].[" + [GBL Version].CURRENTMEMBER.PROPERTIES("End Period") + "]")
      } ON 0,
      NON EMPTY {
        [CST Cost Pool].[CST Cost Pool].MEMBERS
      } * {
        [CST Activity].[CST Activity].MEMBERS
      } ON 1
      FROM [CST Pool to Activity Apportionment]
      WHERE (
        [GBL Version].[GBL Version].[Budget],
        [CST Pool to Activity Apportionment Measure].[CST Pool to Activity Apportionment Measure].[Apportioned Amount],
        [GBL Cost Centre].[GBL Cost Centre].[Total Cost Centres]
      )

  - view_name: RPT Stage 1b Pool Settled vs Input
    set_as_default: false
    mdx: |
      SELECT
      NON EMPTY {
        STRTOMEMBER("[GBL Period].[" + [GBL Version].CURRENTMEMBER.PROPERTIES("Start Period") + "]")
        :
        STRTOMEMBER("[GBL Period].[" + [GBL Version].CURRENTMEMBER.PROPERTIES("End Period") + "]")
      } ON 0,
      NON EMPTY {
        TM1FILTERBYLEVEL({TM1SUBSETALL([CST Cost Pool])}, 0)
      } * {
        [CST Pool to Activity Apportionment Measure].[Amount],
        [CST Pool to Activity Apportionment Measure].[Settled Amount],
        [CST Pool to Activity Apportionment Measure].[Apportioned Amount]
      } ON 1
      FROM [CST Pool to Activity Apportionment]
      WHERE (
        [GBL Version].[GBL Version].[Budget],
        [CST Activity].[CST Activity].[Input],
        [GBL Cost Centre].[GBL Cost Centre].[Total Cost Centres]
      )
