cube: CST Profit and Loss Report
views:
  - view_name: RPT Default
    set_as_default: true
    mdx: |
      SELECT
      NON EMPTY CROSSJOIN(
        TM1FILTERBYLEVEL({TM1SUBSETALL([CST Service Line])}, 0),
        TM1FILTERBYLEVEL({TM1SUBSETALL([GBL Cost Centre])}, 0)
      ) ON COLUMNS,
      NON EMPTY TM1FILTERBYLEVEL({TM1SUBSETALL([GBL Account])}, 0) ON ROWS
      FROM [CST Profit and Loss Report]
      WHERE ([GBL Version].[Budget],
             [GBL Period].[Apr FY2025],
             [CST Apportionment Stage].[Post Apportionment],
             [CST Profit and Loss Report Measure].[Amount])
