cube: CST Account to Pool Apportionment
views:
  - view_name: RPT Default
    set_as_default: true
    mdx: |
      SELECT
      NON EMPTY {
        STRTOMEMBER("[GBL Period].[" + [GBL Version].CURRENTMEMBER.PROPERTIES("Start Period") + "]")
        :
        STRTOMEMBER("[GBL Period].[" + [GBL Version].CURRENTMEMBER.PROPERTIES("End Period") + "]")
      } ON 0,
      NON EMPTY {
        DRILLDOWNMEMBER(
          { [GBL Account].[GBL Account].[{overhead_consolidation}] },
          { [GBL Account].[GBL Account].[{overhead_consolidation}] },
          RECURSIVE)
      } * {
        [CST Cost Pool].[CST Cost Pool].MEMBERS
      } ON 1
      FROM [CST Account to Pool Apportionment]
      WHERE (
        [GBL Version].[GBL Version].[Forecast],
        [CST Account to Pool Apportionment Measure].[CST Account to Pool Apportionment Measure].[Apportioned Amount],
        [GBL Cost Centre].[GBL Cost Centre].[Total Cost Centres]
      )
