cube: CST Pool Config
views:
  - view_name: RPT Default
    set_as_default: true
    mdx: |
      SELECT
      NON EMPTY {
        STRTOMEMBER("[GBL Period].[" + [GBL Version].CURRENTMEMBER.PROPERTIES("Start Period") + "]")
        :
        STRTOMEMBER("[GBL Period].[" + [GBL Version].CURRENTMEMBER.PROPERTIES("End Period") + "]")
      } ON 0,
      NON EMPTY {
        [CST Cost Pool].[CST Cost Pool].MEMBERS
      } * {
        [CST Driver].[CST Driver].MEMBERS
      } * {
        [CST Activity].[CST Activity].MEMBERS
      } ON 1
      FROM [CST Pool Config]
      WHERE (
        [GBL Version].[GBL Version].[Budget],
        [CST Pool Config Measure].[CST Pool Config Measure].[Pool to Activity Basis]
      )
